# Generated by Django 5.2.4 on 2025-07-29 13:51

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_city_options_alter_flight_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="image",
            field=models.ImageField(
                null=True, upload_to=airport.models.route_image_path
            ),
        ),
    ]
