# Generated by Django 5.2.4 on 2025-07-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_route_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="airplane",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="airport.airplane",
            ),
        ),
        migrations.AlterField(
            model_name="flight",
            name="route",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flights",
                to="airport.route",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="departure_airport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departure_routes",
                to="airport.airport",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination_routes",
                to="airport.airport",
            ),
        ),
    ]
