# Generated by Django 5.2.4 on 2025-07-31 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_alter_flight_airplane_alter_flight_route_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"ordering": ["city", "country"]},
        ),
        migrations.RenameField(
            model_name="city",
            old_name="name",
            new_name="city",
        ),
        migrations.RemoveField(
            model_name="airport",
            name="country",
        ),
        migrations.AlterUniqueTogether(
            name="city",
            unique_together={("city", "country")},
        ),
    ]
